### ISSUE TITLE
input templates

### ISSUE THREAD

**Issue by edanweis** [edanweis/LCC#1]
Provide a template for project typologies, based on the case studies already entered into the calculator. Can projects be grouped by similar inputs? This would make it faster - people modify pre-filled values.

**Comment by pjconrad** [comment]
I've uploaded the current case studies to the google drive at this link. (we will be doing about 20 in total) https://drive.google.com/open?id=1bqvNg5bNlHL3261N7Bl331cLC1MxBfLj 
There are 3 projects and 2 excel files for each project. The one with ALT at the end of the file name is what the project carbon footprint COULD have been if we made some design changes. The other file is the carbon footprint of the project as built. You will notice the ALT has a lower carbon footprint, increased sequestration, and offsets the carbon footprint much faster. Renderings for these projects and what "could have been" are also in this folder.
