### ISSUE TITLE
I need to know specific dimensions for what a small, medium, or large tree and/or shrub is

### ISSUE THREAD

**Issue by pjconrad** [edanweis/LCC#109]

**Comment by edanweis** [comment]
Duplicate issue for any other sources/sinks/costs whose units are defined ambiguously?

**Comment by pjconrad** [comment]
I don't think this is an issue - we just need to add some text to define
what we mean by small (i.e. small = 0'-2', medium =2'-4', large =4'+). I
just need to dig back to confirm thoseand then you can add the text to the
app.

**Comment by CNimmo16** [comment]
Updated in the parsing spreadsheet and database (can be seen on staging site).

**Comment by CNimmo16** [comment]
@edanweis Edan could you let me know how to update the reference spreadsheet with these changes so they are not lost, do you want me to pull request the data-utils branch with the updated xlsx, or is it one of the google sheets?

**Comment by edanweis** [comment]
Just received your email with the latest parsing.csv. I'll merge it into the data-utils branch, that should be fine.
