### ISSUE TITLE
Change web tab logo to match website (Tyler will have this - its just the green slash)

### ISSUE THREAD

**Issue by pjconrad** [edanweis/LCC#114]

**Comment by edanweis** [comment]
Ok, I'm guessing tab logo = favicon.ico

**Comment by pjconrad** [comment]
yes, i prefer the icon used on the tab for the website. it is just the
green slash - super simple.
[image: image.png]

**Comment by edanweis** [comment]
#67 is a different issue?

**Comment by pjconrad** [comment]
Icon link here: 
https://drive.google.com/open?id=1EpJyh1hkZQJOqvqkmR2Z4gkHFKZvBfdm
