### ISSUE TITLE
Sorting inputs

### ISSUE THREAD

**Issue by edanweis** [edanweis/LCC#3]
Pamela, can you provide a list of all source/sink potential impacts sorted by their "potential" impact on CO2 in descending order? I'm seeing "CO2-eq/unit/yr" but not sure if that is comparative across different items (eg. trees/maintenance, etc.)

This will help prioritize inputs from users, which might make more to least

**Comment by pjconrad** [comment]
Hi Edan,
The attached spreadsheet has inputs sorted by their category type. See the red highlighted tabs for the updated info. 

In the "Carbon Source" tab, the items by type are grouped and sorted by highest embodied carbon (Total kg CO2 - highlighted in yellow). For example, all of the paving material choices are given the quantity of 1 SF (dark green cells), so you can see the range of embodied carbon for paving in the yellow cells. 

In the "Tree Shrub Comparison" tab, all trees and shrub types (by region, size etc) are sorted by those that would sequester the most over 40 years, sorted from high to low. 

I don't think that we have the information to compare across sources, sinks and costs, and i'm not sure it is relevant, but definitely open to discussing. For example, planting plans has such a low embodied carbon value, it is just carried in the contingency %. We were not able to determine a value of embodied carbon for each sf of planting. Rather the sequestration for plants is more significant to factor. Mostly, I imagine that people will need to select a type of paving (or wall etc.) and will use this to pick the one with the lowest embodied carbon and also select the plants with the highest sequestration. 

It might be good to walk you through the spreadsheet some time. I'd be open to a call this Friday if you are available.  

[190101_LCC TEMPLATE.xlsx](https://github.com/edanweis/LCC/files/2720020/190101_LCC.TEMPLATE.xlsx)
