### ISSUE TITLE
Supplier provided inputs.

### ISSUE THREAD

**Issue by edanweis** [edanweis/LCC#4]
Users could have the option to send an automated email to a supplier, introducing the project and requesting the data, in return for advertising their products in the calculator.

Next time a user goes to fill in "project site grading" they will see pre-filled options based on real contractors.

**Comment by pjconrad** [comment]
Sounds like a great idea. I could especially see how we could change how product/material suppliers build their products and provide information on them. 

Some manufacturers are providing EPDs (environmental product declarations) these days which list the embodied carbon numbers, but hasn't really made it to the landscape realm yet. Those manufacturers need motivation on why to provide it, which would be exposure to more customers/more sales.
