### ISSUE TITLE
Carbon Tracking / carbon paths

### ISSUE THREAD

**Issue by edanweis** [edanweis/LCC#6]
This is a slight pivot from 'calculator' to 'recommender'. The idea is to reward/support design decisions, instead of celebrate built projects. In a way, carbon footprints are something "left behind" so maybe we use the phrase "carbon tracking", or carbon pathways, suggest alternative solutions, or exemplary outcomes from similar projects. This might encourage adoption from projects under development and engage more suppliers because their ads are more targeted to LAs specifically looking for alternative products/services. Basically a carbon path tool may have a greater social impact as a decision support tool, rather than only a calculate footprints of finished projects.

**Comment by pjconrad** [comment]
Good idea Edan. I like the overall description as carbon tracking with tools that provide pathways to reduce your footprint.
