### ISSUE TITLE
Add period on main page after “Tool”

### ISSUE THREAD

**Issue by edanweis** [edanweis/LCC#75]

**Comment by pjconrad** [comment]
@edanweis not seeing this picked up on the staging site.

**Comment by edanweis** [comment]
@pjconrad Cameron is deploying his local changes to the staging site. He's not pulling any of my changes into his branches. I'm merging his PRs and deploying them to the other staging site (https://lcc-staging.surge.sh), but not as often as him.

**Comment by edanweis** [comment]
btw, in GitHub, you can see the commits made against issues that have been closed by clicking the hash, eg: https://github.com/edanweis/LCC/commit/0f838bcd529eb2e8bce21151a99ccd94ae815caf
