### ISSUE TITLE
Toggle between slider and keyboard input for calculator inputs

### ISSUE THREAD

**Issue by edanweis** [edanweis/LCC#84]

**Comment by CNimmo16** [comment]
Wondering what the best way of implementing this is in terms of ux? I could add an "enter manually" button to every field that would switch out the slider for an input box, but arguably this would clutter the ui. A more elegant solution might be that if you drag the slider to the far left, it switches from "n" to "< n", and an input appears on the left side of the slider for an exact quantity, and vice versa for the right. Any thoughts or suggestions?

**Comment by pjconrad** [comment]
If the user has exact quantities available, I think we want to let them input those numbers directly without going to the sliders. Would it be possible to override/type directly into the number that the slider quantity generates?

**Comment by CNimmo16** [comment]
No reason why not, currently the text snippet there is only displaying once a slider is adjusted above the zero position. I can replace it with an input field that is always there but defaults to zero, and updates whenever the slider is moved, which can also be typed into manually.
