### ISSUE TITLE
Add % hardscape/softscape to project summary

### ISSUE THREAD

**Issue by edanweis** [edanweis/LCC#86]

**Comment by edanweis** [comment]
Is this worth adding, given it has been commented as an ambiguous metric, and doesn't actually drive any data, just used for onboarding, as a kind of method of engagement and data collection?

**Comment by CNimmo16** [comment]
This isn't currently saved in the google sheets, it would need to be added in order to implement this feature. As Edan says, the value is purely based on what the user selects during onboarding, so even if this was implemented wouldn't it potentially display inaccurate information if the elements added to the project didn't match the original % the user chose?

**Comment by CNimmo16** [comment]
@pjconrad I hadn't noticed previously that the spreadsheet calculates the planted/impervious area based on the elements in the project (I'm not an expert but I'm assuming that's the equivalent of softscape/hardscape?). Would you like me to use that metric for this feature?

**Comment by pjconrad** [comment]
Yes, that would be great. I knew we had it somewhere!

Pamela

**Comment by edanweis** [comment]
We can't add this to the project summary because it will be inconsistent
with the values entered via on-boarding. There are two inputs effectively
driving the same value displayed in the app:

The on-boarding percentage is used as a rough estimate for us to gather
data without needing users to sign up (although I'm not sure this is being
written to the db).

if we display the hard/soft percentage from the Google sheet it would be
different from the on boarding amount because of the zero state showing 0
percent.

**Comment by pjconrad** [comment]
@CNimmo16 @edanweis This shows up in the scorecard, so as long as its accurate here, we don't need to add it elsewhere.

**Comment by edanweis** [comment]
Yes, it will appear accurately in the scorecard, but will likely differ from the user's onboarding estimate %.
