### ISSUE TITLE
Add Primary Source Data citation

### ISSUE THREAD

**Issue by pjconrad** [edanweis/LCC#9]
Primary sources are 1 and 4. Main source for embodied carbon values comes from source 4. Main source for sequestration rates comes from 1. 

--

1.	McPherson, EG.; Simpson, JR. (1999). Carbon dioxide reduction through urban forestry: Guidelines for professional and volunteer tree planters. Gen. Tech. Rep. PSWGTR-171. Albany, CA: Pacific Southwest Research Station, Forest Service, U.S. Department of Agriculture

2.	de Klein, J. J., & van der Werf, A. K. (2014). Balancing carbon sequestration and GHG emissions in a constructed wetland. Ecological engineering, 66, 36-42.

3.	Gu, C., Crane, J., Hornberger, G., & Carrico, A. (2015). The effects of household management practices on the global warming potential of urban lawns. Journal of environmental management, 151, 233-242.

4.	“ATHENA® Impact Estimator for Buildings V5.2 Software and Database Overview.” (2017). Athena Sustainable Materials Institute, Ontario, Canada

5.	Strain, L. (2017). Time Value of Carbon. Retrieved from http://www.siegelstrain.com/wp-content/uploads/2017/09/Time-Value-of-Carbon-170530.pdf (Last accessed 09/28/2018)

**Comment by edanweis** [comment]
Great thanks Pamela

**Comment by edanweis** [comment]
Add to bottom of project input page?

**Comment by pjconrad** [comment]
See below for minor text modifications. This could be displayed at the bottom of the input pages per each category (i.e. only the Sources references would go under the Sources tab)

Sources
“ATHENA® Impact Estimator for Buildings V5.2 Software and Database Overview.” (2017). Athena Sustainable Materials Institute, Ontario, Canada.

Sinks
de Klein, J. J., & van der Werf, A. K. (2014). Balancing carbon sequestration and GHG emissions in a constructed wetland. Ecological engineering, 66, 36-42.

Gu, C., Crane, J., Hornberger, G., & Carrico, A. (2015). The effects of household management practices on the global warming potential of urban lawns. Journal of environmental management, 151, 233-242.

McPherson, EG.; Simpson, JR. (1999). Carbon dioxide reduction through urban forestry: Guidelines for professional and volunteer tree planters. Gen. Tech. Rep. PSWGTR-171. Albany, CA: Pacific Southwest Research Station, Forest Service, U.S. Department of Agriculture.

Costs
Banks, J. L., & McConnell, R. (2015, April). National Emissions from Lawn and Garden Equipment. In International Emissions Inventory Conference, San Diego.

Gu, C., Crane, J., Hornberger, G., & Carrico, A. (2015). The effects of household management practices on the global warming potential of urban lawns. Journal of environmental management, 151, 233-242.

Lal, R. (2004). Carbon emissions from farm operations. Environ. Int. 30 (7), 981-990.


For a full list of references, refer to Resources page of website.

**Comment by pjconrad** [comment]
If it happens to be too much text to go below the inputs, it could also be added to the menu tab as "References" and go to its own page when selected.
