### ISSUE TITLE
Add the total CO2 qty for each element.

### ISSUE THREAD

**Issue by pjconrad** [edanweis/LCC#95]
Add a number next to input slider in edit project page. Take value from item's total CO2 - cell in Google Sheet.

**Comment by edanweis** [comment]
Need to design UI in already cramped area to include this.

**Comment by pjconrad** [comment]
let's discuss the best way to handle this.

**Comment by pjconrad** [comment]
Clarification: We want to add the total CO2 per line item, not the total CO2 per 1 unit of the element. 

Sources:
![image](https://user-images.githubusercontent.com/46090868/64225451-5947c900-ce90-11e9-80b2-d2bc1c8bfd98.png)

Sinks: Trees/Lawns/Wetlands
![image](https://user-images.githubusercontent.com/46090868/64225770-bd1ec180-ce91-11e9-8fbb-76e1b123416d.png)

Sinks: Shrubs
![image](https://user-images.githubusercontent.com/46090868/64225826-e93a4280-ce91-11e9-9f61-db4df94c83b2.png)

Costs:
![image](https://user-images.githubusercontent.com/46090868/64225889-2b638400-ce92-11e9-81de-81bf223e3cf9.png)

**Comment by pjconrad** [comment]
And I think the totals could go here. Maybe green text for CO2 sequestration  and red text for emissions?

![image](https://user-images.githubusercontent.com/46090868/64226400-1daefe00-ce94-11e9-8b03-3d65d6495b45.png)

**Comment by CNimmo16** [comment]
See #125 - co2 values for all elements added except fertilizer, for which values are not currently being calculated correctly in spreadsheet.

**Comment by pjconrad** [comment]
@CNimmo16  The sink sequestration CO2 quantities are not showing up on mobile. Also, the growth zone from the maps is not remembered after I have entered it originally from another device.

**Comment by edanweis** [comment]
@CNimmo16 From memory, the growth zone is a hardcoded element which was probably not fetching the cell value as a computed property or something.

**Comment by CNimmo16** [comment]
The co2 quantities for trees, lawn and shrubs are not list per type (height, decidious/evergreen) in the spreadsheet. Instead the average is calculated with some very complicated looking math. So for these categories I've just listed the average at the top of the list of sliders. On mobile this does make it difficult to see where the value is.

**Comment by CNimmo16** [comment]
As Edan says, the growth zone is just a static element at the moment.
